[package]
name = "chip8-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", default-features = false }
fastrand = "2.1.0"
rodio = { version = "0.19.0", default-features = false }
